# trusty is required for oraclejdk9
dist: trusty

language: java

jdk: openjdk14

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tesseract-ocr
  - sudo apt-get install -y tesseract-ocr-eng
  - sudo apt-get install -y tesseract-ocr-fra

addons:
  apt:
    update: true

jobs:
  include:
    - stage: build project
      script:
        - mvn clean install -DskipTests
    - stage: test and verify
      script:
        - mvn verify
    - stage: generate coverage reporte
      script:
        - mvn jacoco:report coveralls:report