# trusty is required for oraclejdk9
dist: trusty

language: java

jdk: openjdk14

before_install:
  - sudo apt-get update
  - sudo apt-get tesseract-ocr
  - sudo apt-get tesseract-ocr-eng
  - sudo apt-get tesseract-ocr-fra

addons:
  apt:
    update: true
jobs:
  include:
    - stage: build
      script:
        - mvn clean install -DskipTests
    - stage: test
        - mvn verify
    - stage: coverage
        - mvn jacoco:report coveralls:report