language: java

sudo: false

# trusty is required for oraclejdk9
dist: trusty

services:
  - docker

install: true

jobs:
  include:
    - stage: build on docker
      script:
        - docker build -t scrooge-api .
    - stage: package
      script:
        # tests are executed on docker build stage
        - mvn clean package -DskipTests=true

after_success:
  - mvn jacoco:report coveralls:report