language: java

sudo: false

# trusty is required for oraclejdk9
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build on docker
      script:
        - docker build -t scrooge-api .
install: true
script: mvn clean package -DskipTests=true

after_success:
  - mvn jacoco:report coveralls:report