dist: focal

language: java

jdk: openjdk14

addons:
  apt:
    update: true

jobs:
  include:
    - stage: build and install project
      script:
        - mvn clean install -DskipTests
    - stage: verify and generate coverage report
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y tesseract-ocr
        - sudo apt-get install -y tesseract-ocr-eng
        - sudo apt-get install -y tesseract-ocr-fra
      script:
        - mvn verify jacoco:report coveralls:report