language: java

sudo: false

# trusty is required for oraclejdk9
dist: trusty

jdk: openjdk14

before_install:
  - sudo apt-get update
  - sudo apt-get -y install tesseract-ocr
  - sudo apt-get -y install tesseract-ocr-eng
  - sudo apt-get -y install tesseract-ocr-fra

after_success:
  - mvn jacoco:report coveralls:report