language: java

sudo: false

# trusty is required for oraclejdk9
dist: trusty

jdk: openjdk14

services:
  - docker

install: true

jobs:
  include:
    - stage: build on docker
      script:
        - docker build -t scrooge-api --build-arg env=ci .