language: java

sudo: false

# trusty is required for oraclejdk9
dist: trusty

jdk: openjdk14

services:
  - docker

before_install:
  - sudo apt-get tesseract-ocr
  - sudo apt-get tesseract-ocr-eng
  - sudo apt-get tesseract-ocr-fra

jobs:
  include:
    - stage: build
      script:
        - mvn clean install -DskipTests
    - stage: test
        - mvn verify
    - stage: coverage
        - mvn jacoco:report coveralls:report